name: Calier test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: channel1
    contracts:
    - id: pixelterior-go

organizations:
  - mspid: org-msp
    identities:
      certificates:
      - name: 'client'
        clientPrivateKey:
          path: './generated/client.key'
        clientSignedCert:
          path: './generated/client.pem'
    connectionProfile:
      path: './generated/connection_property_org-msp.json'
# Uncomment the next line only if you want to try this network configuration file binding to fabric:2.2, it's not required for fabric-gateway binding
      discover: true
